from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from app.core.config import settings
from app.api.v1.router import router as api_router
from app.storage.db import engine, Base

Base.metadata.create_all(bind=engine)

tags_metadata = [
    {
        "name": "Scans",
        "description": (
            "Multi-modal fraud detection endpoints. Each modality has a dedicated "
            "ML pipeline and returns a standardised `ScanResponse` with risk score, "
            "risk tier, confidence, signals, and (optionally LLM-generated) explanation."
        ),
        "externalDocs": {
            "description": "HuggingFace model catalogue",
            "url": "https://huggingface.co/models",
        },
    },
    {
        "name": "General",
        "description": "Health checks and system status.",
    },
]

app = FastAPI(
    title=settings.PROJECT_NAME,
    description="""
# Scam Detection Platform API

A multi-modal fraud detection service that combines transformer-based ML classifiers,
heuristic analysis engines, and optional LLM enrichment (via Ollama) to evaluate
content across **five modalities**.

## Modalities

| Modality | Model / Engine | Endpoint |
|----------|---------------|----------|
| **Email** | `cybersectony/phishing-email-detection-distilbert_v2.1` + keyword analysis | `POST /scan/email` |
| **URL** | `darshan8950/phishing_url_detection_BERT` + heuristic features | `POST /scan/url` |
| **File** | Magic-byte, pattern, entropy, extension-spoofing analysis | `POST /scan/file` |
| **Audio** | librosa spectral features (MFCC, centroid, bandwidth, pitch) | `POST /scan/audio` |
| **Prompt** | `protectai/deberta-v3-base-prompt-injection-v2` | `POST /scan/prompt` |
| **Unified** | Weighted aggregation of all the above | `POST /scan/unified` |

## Response Format

Every scan endpoint returns a **`ScanResponse`** object:

| Field | Type | Description |
|-------|------|-------------|
| `risk_score` | `float` | 0 – 100 risk score |
| `risk_tier` | `string` | `safe` · `low` · `medium` · `high` · `critical` |
| `confidence` | `float` | 0.0 – 1.0 model confidence |
| `signals` | `string[]` | Threat indicators identified |
| `explanation` | `string` | Human-readable explanation |
| `analyst_summary` | `string` | Technical analyst summary |
| `recommended_action` | `string` | Suggested next step |

## LLM Enrichment

When **Ollama** is running locally (`qwen2.5:0.5b`), `explanation`, `analyst_summary`, and
`recommended_action` are generated by the LLM. When Ollama is unavailable, the API
automatically falls back to deterministic rule-based text — no functionality is lost.

## Quick Start

```bash
# Start the backend
cd backend && python main.py        # → http://localhost:8000

# Interactive docs
open http://localhost:8000/docs      # Swagger UI
open http://localhost:8000/redoc     # ReDoc
```
    """,
    version="2.0.0",
    terms_of_service="http://example.com/terms/",
    contact={
        "name": "Scam Detection API Support",
        "url": "http://www.example.com/support",
        "email": "support@example.com",
    },
    license_info={
        "name": "Apache 2.0",
        "url": "https://www.apache.org/licenses/LICENSE-2.0.html",
    },
    openapi_url=f"{settings.API_V1_STR}/openapi.json",
    docs_url="/docs",
    redoc_url="/redoc",
    openapi_tags=tags_metadata,
    swagger_ui_parameters={
        "docExpansion": "list",
        "defaultModelsExpandDepth": 1,
        "filter": True,
        "tryItOutEnabled": True,
    },
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.BACKEND_CORS_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(api_router)


@app.get(
    "/",
    tags=["General"],
    summary="API Root",
    description="Returns a welcome message confirming the API is running. Use `/health` for a structured health check.",
    operation_id="root",
    responses={
        200: {
            "description": "API is running.",
            "content": {
                "application/json": {
                    "example": {
                        "message": "Scam Detection Platform API v2.0 Running",
                        "docs": "/docs",
                        "redoc": "/redoc",
                        "health": "/health",
                    }
                }
            },
        }
    },
)
async def root():
    return {
        "message": "Scam Detection Platform API v2.0 Running",
        "docs": "/docs",
        "redoc": "/redoc",
        "health": "/health",
    }
